default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: rails-7-passkey-demo_development


test:
  <<: *default
  database: rails-7-passkey-demo_test
